name: mvn -B site -Pdeploy

on:
  create:
    tags:
      - v*      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: checkout
      uses: actions/checkout@v2.5.0

    - name: Set up JDK 17
      uses: actions/setup-java@v3.6.0
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B site --file pom.xml

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/site # The folder the action should deploy.
      
